import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: ' ¿Qué leo?',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className='px-4 m-auto grid min-h-screen  max-w-screen-lg  grid-rows-[60px,1fr,60px] gap-4'>
          <nav className='flex items-center text-2xl font-semibold'>
            ¿Qué leo?
          </nav>
          <section>{children}</section>
          <footer className='flex items-center justify-center'>
            <p>By <span className='font-semibold'> @ffranco14</span></p>
            </footer>
        </main>
      </body>
    </html>
  )
}
